---
- name: Workflow Job Template for Patterns Research
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx

  vars:
    awx_host: "https://localhost:8043"
    awx_username: "admin"
    awx_password: "*****"  # Replace with your actual admin password
    validate_certs: false
    organization_name: "Research"
    project_name: "Research Project"
    inventory_name: "Research Inventory"

  tasks:
    - name: Create an organization
      awx.awx.organization:
        name: "{{ organization_name }}"
        description: "Default organization for AWX demos"
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present

    - name: Create a project
      awx.awx.project:
        name: "{{ project_name }}"
        description: "Research project with sample playbooks"
        organization: "{{ organization_name }}"
        scm_type: git
        scm_url: "https://github.com/ansible/ansible-examples.git"
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present
      register: project_result

    - name: Wait for project to sync
      awx.awx.project_update:
        project: "{{ project_name }}"
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        wait: true
      when: project_result is changed

    - name: Create an inventory
      awx.awx.inventory:
        name: "{{ inventory_name }}"
        description: "Research inventory"
        organization: "{{ organization_name }}"
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present

    # - name: Create a host in the inventory
    #   awx.awx.host:
    #     name: "localhost"
    #     description: "Research host"
    #     inventory: "{{ inventory_name }}"
    #     controller_host: "{{ awx_host }}"
    #     controller_username: "{{ awx_username }}"
    #     controller_password: "{{ awx_password }}"
    #     validate_certs: "{{ validate_certs }}"
    #     state: present

    - name: Create a job template for ping
      awx.awx.job_template:
        name: "Ping Hosts"
        job_type: "run"
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        playbook: "language_features/loop_nested.yml"
        credential: "Research Credential"  # You'll need to create this manually (or add a task for it)
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present
      register: ping_template

    - name: Create a job template for facts
      awx.awx.job_template:
        name: "Gather Facts"
        job_type: "run"
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        playbook: "language_features/loop_nested.yml"
        credential: "Research Credential"  # You'll need to create this manually (or add a task for it)
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present
      register: facts_template

    # - name: Create a workflow job template
    #   awx.awx.workflow_job_template:
    #     name: "Research Workflow"
    #     description: "A workflow job template created via Ansible"
    #     organization: "{{ organization_name }}"
    #     controller_host: "{{ awx_host }}"
    #     controller_username: "{{ awx_username }}"
    #     controller_password: "{{ awx_password }}"
    #     validate_certs: "{{ validate_certs }}"
    #     state: present
    #   register: workflow_template

    - name: Create a workflow job template
      awx.awx.workflow_job_template:
        name: "Research Workflow"
        description: "A workflow job template created via Ansible"
        organization: "{{ organization_name }}"
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        survey_enabled: true
        survey_spec:
          name: "Research Workflow Survey"
          description: "Survey for Research Workflow"
          spec:
            - question_name: "Environment"
              question_description: "Target environment for deployment"
              required: true
              type: "multiplechoice"
              variable: "environment"
              choices: "Development\nStaging\nProduction"
              default: "Development"
            - question_name: "Deployment Version"
              question_description: "Version to deploy"
              required: true
              type: "text"
              variable: "version"
              default: "1.0.0"
            - question_name: "Deployment Notes"
              question_description: "Additional notes for this deployment"
              required: false
              type: "textarea"
              variable: "notes"
              default: ""
            - question_name: "Notification Email"
              question_description: "Email to send notifications to"
              required: true
              type: "text"
              variable: "email"
              default: "user@example.com"
              regex: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        state: present
      register: workflow_template


    - name: Create workflow nodes
      awx.awx.workflow_job_template_node:
        workflow_job_template: "Research Workflow"
        unified_job_template: "{{ item.template }}"
        identifier: "{{ item.identifier }}"
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present
      loop:
        - { template: "Ping Hosts", identifier: "node1" }
        - { template: "Gather Facts", identifier: "node2" }
      register: workflow_nodes

    - name: Create workflow node connections
      awx.awx.workflow_job_template_node:
        workflow_job_template: "Research Workflow"
        identifier: "node2"
        success_nodes:
          - "node1"
        controller_host: "{{ awx_host }}"
        controller_username: "{{ awx_username }}"
        controller_password: "{{ awx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present

